start-dev-backend:
	npm run dev

start-dev-frontend:
	make -C ../frontend start-dev

start-dev:
	make start-dev-backend & make start-dev-frontend

start-backend:
	npm run start

start-frontend:
	make -C ../frontend start

start:
	make start-backend & make start-frontend